### ISSUE TITLE
Contact original developer

### ISSUE THREAD

**Issue by Photon89** [Photon89/lightspeed#1]
@iskunk: Well, basically, that's it. :smiley: 

Here's a GTK2 port (in progress) for your Light Speed! simulator. Please let me know, if you don't like me tinkering with it!

**Comment by iskunk** [comment]
Yo.

We had a short discussion over e-mail, but the gist is I'm happy to see this get some much-needed TLC and modernization work :smiley:

I can't do heavy lifting on this, but will be happy to help here and there as needed.

**Comment by Photon89** [comment]
Thanks for your support! :smiley:  Since the contacting is done, I guess, this issue can be closed. A first closed issue, yay!
